#!/opt/anaconda/envs/env_ewf_wfp_02_03_01/bin/python

import os
import sys

sys.path.append('/'.join([os.environ['_CIOP_APPLICATION_PATH'], 'util']))
sys.path.append('../util')

from s2_whittaker_helpers import *

import string
import atexit
import pandas as pd
import cioppy
import datetime

ciop = cioppy.Cioppy()
    
# define the exit codes
SUCCESS = 0
ERR_RESOLUTION = 10
ERR_STAGEIN = 20
ERR_NO_OUTPUT = 30

# add a trap to exit gracefully
def clean_exit(exit_code):
    log_level = 'INFO'
    if exit_code != SUCCESS:
        log_level = 'ERROR'  

    msg = {SUCCESS: 'Processing successfully concluded',
           ERR_RESOLUTION: 'Could not resolve Sentinel-2 product enclosure',
           ERR_STAGEIN: 'Could not stage-in Sentinel-2 product', 
           ERR_NO_OUTPUT: "Missing output"
    }
 
    ciop.log(log_level, msg[exit_code])  

def main():
        
    ciop = cioppy.Cioppy()
    
    os.chdir(ciop.tmp_dir)
    
    band_to_process = ciop.getparam('band')
    delta_day = int(ciop.getparam('delta_time_output'))

    data_pipeline_parameters = dict()    
    
    data_pipeline_parameters['username'] = ciop.getparam('_T2Username')
    data_pipeline_parameters['api_key'] = ciop.getparam('_T2ApiKey')

    creds = '{}:{}'.format(data_pipeline_parameters['username'],
                           data_pipeline_parameters['api_key'])

    for input in sys.stdin:
        
        #output_name = os.path.join(ciop.tmp_dir, input.rstrip().split(',')[0])

        ciop.log('INFO', 'Processing tile {}'.format(input.rstrip()))
        
        local_subtile = ciop.copy(input.rstrip(),
                                  ciop.tmp_dir,
                                  extract=False)
        
        ciop.log('INFO', 'Processing local tile {}'.format(local_subtile))

        sub_tile = pd.read_pickle(local_subtile, 'gzip')
        
        

        sub_tile = sub_tile.merge(sub_tile.apply(lambda row: analyse_subtile(row, data_pipeline_parameters, band_to_process), axis=1),
                                  left_index=True,
                                  right_index=True)

        if sub_tile.duplicated(['day']).any():
    
            duplicated_day = sub_tile[sub_tile.duplicated(['day'])].day.values[0]
            duplicates = sub_tile[sub_tile.day == duplicated_day]

            for index, row in duplicates.iterrows():

                if np.isnan(duplicates[band_to_process][index][0]).all():
                
                    sub_tile  = sub_tile.drop([index])
        
        ciop.log('INFO', 'Smoothing local tile {}'.format(local_subtile))
        dates = sub_tile['jday']

        
        
        # the generate_dates function creates a list of days with a delta time=5
        full_dates = generate_dates(startdate_string=list(dates)[0], enddate_string=list(dates)[-1], delta=1)
        # Parameter to be set in metadata 
        full_period = '{}_{}'.format(fromjulian(full_dates[0]).strftime('%Y%m%d'),fromjulian(full_dates[-1]).strftime('%Y%m%d'))
        
        # the date_mask array is False when there is no product associated to that date.
        # this is needed by the whittaker function in the interpolation step.
        date_mask = np.array([True if x in list(dates) else False for x in full_dates])

        data_stack = np.stack(sub_tile[band_to_process])
        
        mask_stack = np.stack(sub_tile['SCL_mask'])
        
        print('mask_stack.shape = {}'.format(mask_stack.shape))
        
        result = np.apply_along_axis(whittaker, 0, data_stack, date_mask, band_to_process)
        
        print('result.shape = {}'.format(result.shape))
        
        ### Creating s GeoTiff ###
        ciop.log('INFO', 'Create the s GeoTIFF product for local tile {}'.format(local_subtile))
        geo_transform = sub_tile['geo_transform'].values[0][0]
        projection = sub_tile.projection.unique()[0]
        band_number = 1
        cols = result.shape[1]
        rows = result.shape[2]

        print('s', band_number, cols, rows)

        drv = gdal.GetDriverByName('GTiff')

        ds = drv.Create('temp_s_{}_{}.tif'.format(band_to_process, os.path.basename(local_subtile)), 
                        cols, rows, 
                        band_number, 
                        gdal.GDT_Int16)

        log10_scale100 = lambda x: 0 if np.isnan(x) else(0 if x<=0 else 100*np.log10(x))
        vfunc_log_scale100 = np.vectorize(log10_scale100)
        S_grid = vfunc_log_scale100(result[0])
        
        ds.SetGeoTransform(geo_transform)
        ds.SetProjection(projection)
        ds.GetRasterBand(1).WriteArray(S_grid, 0, 0)
        ds.GetRasterBand(1).SetDescription('s')
        ###Added Metadata even for lag1 , Sgrid
        metadata = dict()
        metadata['full_period'] = full_period
        ds.GetRasterBand(1).SetMetadata(metadata)
        
        ds.FlushCache()
        
        # Creating the lag1corr GeoTiff
        ciop.log('INFO', 'Create the Lag-1 GeoTIFF product for local tile {}'.format(local_subtile))
        geo_transform = sub_tile['geo_transform'].values[0][0]
        projection = sub_tile.projection.unique()[0]
        band_number = 1
        cols = result.shape[1]
        rows = result.shape[2]

        print('Lag-1', band_number, cols, rows)
        drv = gdal.GetDriverByName('GTiff')

        ds = drv.Create('temp_lag1_{}_{}.tif'.format(band_to_process, os.path.basename(local_subtile)), 
                        cols, rows, 
                        band_number, 
                        gdal.GDT_Float32)


        
        ds.SetGeoTransform(geo_transform)
        ds.SetProjection(projection)
        ds.GetRasterBand(1).WriteArray(result[1], 0, 0)
        ds.GetRasterBand(1).SetDescription('lag1')
        ###Added Metadata even for lag1 , Sgrid
        metadata = dict()
        metadata['full_period'] = full_period
        ds.GetRasterBand(1).SetMetadata(metadata)
        ds.FlushCache()
        
        ### Creating original values GeoTiff ###
        ciop.log('INFO', 'Create the original {} GeoTIFF product for local tile {}'.format(band_to_process, local_subtile))
        band_number = data_stack.shape[0]
        cols = data_stack.shape[1]
        rows = data_stack.shape[2]

        ciop.log('DEBUG', ' '.join(['original values', str(band_number), str(cols), str(rows)]))

        drv = gdal.GetDriverByName('GTiff')

        ds = drv.Create('temp_original_{}_{}.tif'.format(band_to_process, os.path.basename(local_subtile)),
                        cols, rows, 
                        band_number, 
                        gdal.GDT_Int16)

        ds.SetGeoTransform(geo_transform)
        ds.SetProjection(projection)
        ds.FlushCache()
        
        ds = gdal.Open('temp_original_{}_{}.tif'.format(band_to_process, os.path.basename(local_subtile)), gdal.OF_UPDATE)

        for index, band in enumerate(range(0, band_number)):

            
            product_date = datetime.datetime.strptime(dates[index], '%Y%j').date()
            date = '{}{:02d}{:02d}'.format(product_date.year, product_date.month, product_date.day)
            
            metadata = dict()
            metadata['date'] = date
            metadata['jdate'] = dates[index]
            metadata['full_period'] = full_period
            
            #ORIGINAL band 
            if band_to_process == 'NDVI':
                scale10k = lambda x: -3000 if x==-3000 else x*10000
                vfunc_scale = np.vectorize(scale10k,otypes=[np.int16])
                raster_to_write_ori = vfunc_scale(data_stack[index])
            else:
                raster_to_write_ori = data_stack[index]
            
            ds.GetRasterBand(index + 1).WriteArray(raster_to_write_ori, 0, 0)
            ds.GetRasterBand(index + 1).SetDescription(dates[index])
            ds.GetRasterBand(index + 1).SetMetadata(metadata)

        ds.FlushCache()
        
        ### Creating mask values GeoTiff ###
        ciop.log('INFO', 'Create the mask {} GeoTIFF product for local tile {}'.format(band_to_process, local_subtile))
        band_number = mask_stack.shape[0]
        cols = mask_stack.shape[1]
        rows = mask_stack.shape[2]

        ciop.log('DEBUG', ' '.join(['mask values', str(band_number), str(cols), str(rows)]))

        drv = gdal.GetDriverByName('GTiff')

        ds = drv.Create('temp_mask_{}_{}.tif'.format(band_to_process, os.path.basename(local_subtile)),
                        cols, rows, 
                        band_number, 
                        gdal.GDT_Int16)

        ds.SetGeoTransform(geo_transform)
        ds.SetProjection(projection)
        ds.FlushCache()
        
        ds = gdal.Open('temp_mask_{}_{}.tif'.format(band_to_process, os.path.basename(local_subtile)), gdal.OF_UPDATE)

        for index, band in enumerate(range(0, band_number)):
        
            product_date = datetime.datetime.strptime(dates[index], '%Y%j').date()
            date = '{}{:02d}{:02d}'.format(product_date.year, product_date.month, product_date.day)
            
            metadata = dict()
            metadata['date'] = date
            metadata['jdate'] = dates[index]
            metadata['full_period'] = full_period

            ds.GetRasterBand(index + 1).WriteArray(mask_stack[index], 0, 0)
            ds.GetRasterBand(index + 1).SetDescription('SCL mask on {}'.format(dates[index]))
            ds.GetRasterBand(index + 1).SetMetadata(metadata)

        ds.FlushCache()
        
        ### Creating GeoTiff ###
        ciop.log('INFO', 'Create the {} GeoTIFF product for local tile {}'.format(band_to_process, local_subtile))
        
        out_bands = range(0, result.shape[0]-2, delta_day)
        
        band_number = len(out_bands)
        cols = result.shape[1]
        rows = result.shape[2]

        ciop.log('DEBUG', ' '.join([str(band), str(band_number), str(cols), str(rows)]))

        drv = gdal.GetDriverByName('GTiff')

        ds = drv.Create('temp_{}_{}.tif'.format(band_to_process, os.path.basename(local_subtile)), 
                        cols, rows, 
                        band_number, 
                        gdal.GDT_Int16)

        ds.SetGeoTransform(geo_transform)
        ds.SetProjection(projection)
        ds.FlushCache()
        
        ds = gdal.Open('temp_{}_{}.tif'.format(band_to_process, os.path.basename(local_subtile)), gdal.OF_UPDATE)

        delta_day_index=0
        
        for index in out_bands:
            
            ciop.log('DEBUG', '{} initial number of bands: {}'.format(band_to_process,ds.RasterCount))
            
            ciop.log('DEBUG', 'index : {}'.format(index))
            
            product_date = datetime.datetime.strptime(full_dates[index], '%Y%j').date()
            date = '{}{:02d}{:02d}'.format(product_date.year, product_date.month, product_date.day)
            band_is_interpolated = 'False' if full_dates[index] in list(dates) else 'True'
            

            metadata = dict()
            metadata['date'] = date
            metadata['jdate'] = full_dates[index]
            metadata['band_is_interpolated'] = band_is_interpolated
            metadata['full_period'] = full_period
            delta_day_index += 1
            
            ciop.log('DEBUG', 'band index {}'.format(delta_day_index))
            
            ### NAT & SYN bands also scaled if value!=noData
#            if band_to_process == 'NDVI':
#                scale10k = lambda x: -3000 if np.isnan(x) else(-3000 if x==-3000 else x*10000) 
#                vfunc_scale = np.vectorize(scale10k)
#                raster_to_write_nat_syn = vfunc_scale(result[index + 2])
#            else:
#                aster_to_write_nat_syn = result[index + 2]

            ds.GetRasterBand(delta_day_index).WriteArray(result[index + 2]*10000, 0, 0)
            ds.GetRasterBand(delta_day_index).SetDescription(full_dates[index])
            ds.GetRasterBand(delta_day_index).SetMetadata(metadata)
        
        ciop.log('DEBUG', '{} number of bands: {}'.format(band_to_process,ds.RasterCount))
        
        ds.FlushCache()
        
        for result,nodata in dict([('s_{}_{}.tif'.format(band_to_process, os.path.basename(local_subtile)), 0),
                                   ('lag1_{}_{}.tif'.format(band_to_process, os.path.basename(local_subtile)),0),
                                   ('{}_{}.tif'.format(band_to_process, os.path.basename(local_subtile)),-3000 if band_to_process == 'NDVI' else 0),
                                   ('original_{}_{}.tif'.format(band_to_process, os.path.basename(local_subtile)),-3000 if band_to_process == 'NDVI' else 0),
                                   ('mask_{}_{}.tif'.format(band_to_process, os.path.basename(local_subtile)),None)]).items():
            
            cog('temp_{}'.format(result),result,nodata)
        
            ciop.log('INFO', 'Publish {}'.format(result))
            ciop.publish(os.path.join(ciop.tmp_dir, result))

try:
    main()
except SystemExit as e:
    if e.args[0]:
        clean_exit(e.args[0])
    raise
else:
    atexit.register(clean_exit, 0)
